kind: Service
apiVersion: v1
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
  labels:
    app: weave-scope-app-elb
  name: weave-scope-app-elb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 4040
    protocol: TCP
  selector:
    app: weave-scope
    name: weave-scope-app
---
apiVersion: v1
kind: Service
metadata:
  name: scope-np
  labels:
    name: scope-np
spec:
  type: NodePort
  ports:
    - port: 4040
      nodePort: 30080
      name: http
  selector:
    app: weave-scope
    name: weave-scope-app
