apiVersion: v1
kind: Namespace
metadata:
  name: logs
---
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: es-gp2-drives
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  # encrypted: "true" # FIXME: This doesn't work
