apiVersion: v1
kind: ReplicationController
metadata:
  name: elasticsearch-logging
  namespace: kube-system
  labels:
    k8s-app: elasticsearch-logging
    version: v1.0.0
spec:
  replicas: 1
  selector:
    k8s-app: elasticsearch-logging
    version: v1.0.0
  template:
    metadata:
      labels:
        k8s-app: elasticsearch-logging
        version: v1.0.0
    spec:
      containers:
      - image: elasticsearch:5.2.2
        name: elasticsearch-logging
        resources:
          # need more cpu upon initialization, therefore burstable class
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
        - containerPort: 9200
          name: api
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: es-persistent-storage
          mountPath: /data
        - name: config-volume
          mountPath: /usr/share/elasticsearch/config/
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: cluster_name
          value: "test"
      volumes:
      - name: es-persistent-storage
        emptyDir: {}
      - name: config-volume
        configMap:
          name: es-config
