apiVersion: v1
kind: Namespace
metadata:
  name: logs
---
# https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: es-logs
  namespace: logs
  labels:
    k8s-app: es-logs
    version: v1.0.0
spec:
  serviceName: es-logs
  template:
    metadata:
      labels:
        k8s-app: es-logs
        version: v1.0.0
    spec:
      containers:
      - image: elasticsearch:5.2.2
        name: es-logs
        resources:
          # need more cpu upon initialization, therefore burstable class
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
        - containerPort: 9200
          name: api
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: es-persistent-storage
          mountPath: /data
        - name: config-volume
          mountPath: /usr/share/elasticsearch/config/
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: cluster_name
          value: "es-logs"
      volumes:
      - name: config-volume
        configMap:
          name: es-config
      - name: es-persistent-storage
        persistentVolumeClaim:
          claimName: es-persistent-storage
  volumeClaimTemplates:
  - metadata:
      name: es-persistent-storage
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 512Gi
