apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana-logs
  namespace: logs
  labels:
    k8s-app: kibana-logs
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kibana-logs
  template:
    metadata:
      labels:
        k8s-app: kibana-logs
    spec:
      containers:
      - name: kibana-logs
        image: kibana:5.2.2
        resources:
          # keep request = limit to keep this container in guaranteed class
          limits:
            cpu: 100m
          requests:
            cpu: 100m
        env:
          - name: "ELASTICSEARCH_URL"
            value: "http://es-logs:9200"
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP
