apiVersion: v1
kind: Service
metadata:
  name: kibana-logs
  namespace: logs
  labels:
    k8s-app: kibana-logs
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30002
    targetPort: ui
    protocol: TCP
  selector:
    k8s-app: kibana-logs
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana-logs
spec:
  rules:
  - host: kibana-logs.mgmt
    http:
      paths:
      - path: /
        backend:
          serviceName: kibana-logs
          servicePort: 80
